import type { GameMode } from "@/lib/gameModes";

export type WordDifficulty = "easy" | "medium" | "hard";

export const EASY_WORDS = [
  "REACT",
  "REDUX",
  "FETCH",
  "ASYNC",
  "AWAIT",
  "CACHE",
  "ROUTE",
  "STATE",
  "STORE",
  "BUILD",
  "DEBUG",
  "CLONE",
  "MERGE",
  "PARSE",
  "PROPS",
  "HOOKS",
  "LINUX",
  "SHELL",
  "CLASS",
  "ARRAY",
  "INDEX",
  "EVENT",
  "PATCH",
  "CONST",
  "ERROR",
  "LOGIN",
  "INPUT",
  "QUEUE",
  "TOKEN",
  "MONGO",
  "FLASK",
  "NGINX",
  "REDIS",
  "MYSQL",
  "HTTPS",
  "CLOUD",
  "GRAPH",
  "STACK",
  "TRACE",
  "MODEL",
  "TABLE",
  "FIELD",
  "BATCH",
  "BABEL",
  "REMIX",
  "ASTRO",
  "TURBO",
  "WHILE",
  "BREAK",
  "THROW",
  "CATCH",
  "MATCH",
  "SLICE",
  "RANGE",
  "ALIAS",
  "TUPLE",
  "GUARD",
  "UNION",
  "BYTES",
  "FLOAT",
  "MACRO",
  "CARGO",
  "PIXEL",
  "MODAL",
  "YIELD",
  "PRINT",
  "SCOPE",
  "CHUNK",
] as const;

export const MEDIUM_WORDS = [
  "MUTEX",
  "PROXY",
  "PANIC",
  "INODE",
  "CHMOD",
  "SPAWN",
  "CRYPT",
  "VHOST",
  "STASH",
  "KAFKA",
  "VAULT",
  "SHARD",
  "PIVOT",
  "OAUTH",
  "ACTOR",
  "FIBER",
  "MONAD",
  "PROTO",
  "NOMAD",
  "RSYNC",
  "PGSQL",
  "OWASP",
  "AUDIT",
  "TRUST",
  "EMBED",
  "REGEX",
  "HEAPS",
  "REALM",
  "SOLID",
  "CROND",
  "PIPES",
  "STDIO",
  "UNAME",
  "SWIFT",
  "TRAIT",
  "TYPED",
  "AXIOS",
  "PRISM",
  "JOTAI",
  "SCALA",
  "STYLE",
  "THEME",
  "MEDIA",
  "TIMER",
] as const;

export const HARD_ONLY_WORDS = [
  "IOCTL",
  "VNODE",
  "EPOLL",
  "UMASK",
  "BISON",
  "TRECK",
  "SWCRC",
  "ESLNT",
] as const;

export const DAILY_WORDS = [
  "REACT",
  "CACHE",
  "TOKEN",
  "MONGO",
  "REDIS",
  "MYSQL",
  "ROUTE",
  "STATE",
  "STACK",
  "QUERY",
  "FETCH",
  "DEBUG",
  "LINUX",
  "SHELL",
  "PATCH",
  "ASYNC",
  "AWAIT",
  "KAFKA",
  "MUTEX",
  "OAUTH",
  "VAULT",
  "SHARD",
  "CHMOD",
  "IOCTL",
] as const;

function cleanWords(words: readonly string[]) {
  return Array.from(new Set(words.filter((word) => /^[A-Z]{5}$/.test(word))));
}

export const EASY_WORD_POOL = cleanWords(EASY_WORDS);
export const MEDIUM_WORD_POOL = cleanWords(MEDIUM_WORDS);
export const HARD_WORD_POOL = cleanWords(HARD_ONLY_WORDS);
export const DAILY_WORD_POOL = cleanWords(DAILY_WORDS);

export const WORDS = cleanWords([...EASY_WORD_POOL, ...MEDIUM_WORD_POOL, ...HARD_WORD_POOL]);

const EASY_SET = new Set(EASY_WORD_POOL);
const MEDIUM_SET = new Set(MEDIUM_WORD_POOL);

export function getWordDifficulty(word: string): WordDifficulty {
  const normalized = word.toUpperCase();
  if (EASY_SET.has(normalized)) {
    return "easy";
  }
  if (MEDIUM_SET.has(normalized)) {
    return "medium";
  }
  return "hard";
}

export function getWordsByMode(mode: GameMode) {
  switch (mode) {
    case "CLASSIC":
    case "SPEED":
      return cleanWords([...EASY_WORD_POOL, ...MEDIUM_WORD_POOL]);
    case "HARD":
      return cleanWords([...MEDIUM_WORD_POOL, ...HARD_WORD_POOL]);
    case "DAILY":
      return DAILY_WORD_POOL;
    default:
      return cleanWords([...EASY_WORD_POOL, ...MEDIUM_WORD_POOL]);
  }
}

export const WORD_CATEGORIES: Record<string, string> = {
  REACT: "frontend",
  REDUX: "estado",
  FETCH: "rede",
  ASYNC: "linguagem",
  AWAIT: "linguagem",
  CACHE: "performance",
  ROUTE: "navegacao",
  STATE: "frontend",
  STORE: "estado",
  BUILD: "deploy",
  DEBUG: "dev tools",
  CLONE: "git",
  MERGE: "git",
  PARSE: "dados",
  PROPS: "react",
  HOOKS: "react",
  LINUX: "sistema",
  SHELL: "terminal",
  CLASS: "oop",
  ARRAY: "estrutura",
  INDEX: "database",
  EVENT: "browser",
  PATCH: "git / http",
  CONST: "javascript",
  ERROR: "runtime",
  LOGIN: "auth",
  INPUT: "ui / forms",
  QUEUE: "estrutura",
  TOKEN: "seguranca / auth",
  MONGO: "database",
  FLASK: "framework",
  NGINX: "infra",
  REDIS: "database",
  MYSQL: "database",
  HTTPS: "protocolo",
  CLOUD: "infra",
  GRAPH: "estrutura",
  STACK: "estrutura",
  TRACE: "observabilidade",
  MODEL: "dados / ia",
  TABLE: "database",
  FIELD: "database / ui",
  BATCH: "processamento",
  BABEL: "build",
  REMIX: "framework",
  ASTRO: "framework",
  TURBO: "build",
  WHILE: "linguagem",
  BREAK: "linguagem",
  THROW: "linguagem",
  CATCH: "linguagem",
  MATCH: "linguagem",
  SLICE: "arrays",
  RANGE: "linguagem",
  ALIAS: "linguagem",
  TUPLE: "tipo de dado",
  GUARD: "linguagem",
  UNION: "tipo de dado",
  BYTES: "dados",
  FLOAT: "tipo de dado",
  MACRO: "linguagem",
  CARGO: "ferramenta",
  PIXEL: "ui / graficos",
  MODAL: "ui",
  YIELD: "linguagem",
  PRINT: "io",
  SCOPE: "linguagem",
  CHUNK: "bundler",
  MUTEX: "concorrencia",
  PROXY: "rede / infra",
  PANIC: "runtime",
  INODE: "sistema",
  CHMOD: "linux",
  SPAWN: "processo",
  CRYPT: "seguranca",
  VHOST: "infra",
  STASH: "git",
  KAFKA: "mensageria",
  VAULT: "seguranca",
  SHARD: "database",
  PIVOT: "dados",
  OAUTH: "auth",
  ACTOR: "concorrencia",
  FIBER: "runtime",
  MONAD: "funcional",
  PROTO: "protocolo",
  NOMAD: "infra",
  RSYNC: "linux",
  PGSQL: "database",
  OWASP: "seguranca",
  AUDIT: "seguranca",
  TRUST: "seguranca",
  EMBED: "ia",
  REGEX: "linguagem",
  HEAPS: "estrutura",
  REALM: "database",
  SOLID: "arquitetura",
  CROND: "linux",
  PIPES: "terminal",
  STDIO: "io",
  UNAME: "linux",
  SWIFT: "linguagem",
  TRAIT: "oop / rust",
  TYPED: "tipo de dado",
  AXIOS: "biblioteca",
  PRISM: "ferramenta",
  JOTAI: "estado",
  SCALA: "linguagem",
  STYLE: "frontend",
  THEME: "frontend",
  MEDIA: "frontend",
  TIMER: "runtime",
  IOCTL: "sistema",
  VNODE: "sistema",
  EPOLL: "linux",
  UMASK: "linux",
  BISON: "parser",
  TRECK: "rede",
  SWCRC: "checksum",
  ESLNT: "lint",
};

export const WORD_HINTS: Record<string, { category: string; hint: string }> = {
  REACT: { category: "frontend", hint: "biblioteca para construir interfaces" },
  REDUX: { category: "estado", hint: "gerenciamento centralizado de estado" },
  QUERY: { category: "dados", hint: "instrucao para buscar ou filtrar dados" },
  FETCH: { category: "rede", hint: "requisicao assincrona para uma API" },
  ASYNC: { category: "linguagem", hint: "marcador de funcao nao bloqueante" },
  AWAIT: { category: "linguagem", hint: "espera uma Promise resolver" },
  PROXY: { category: "rede / infra", hint: "intermediario entre cliente e servidor" },
  CACHE: { category: "performance", hint: "armazena dados para acesso mais rapido" },
  STACK: { category: "estrutura", hint: "pilha ou conjunto de tecnologias" },
  ROUTE: { category: "navegacao", hint: "define um caminho da aplicacao" },
  STATE: { category: "frontend", hint: "dados que controlam a interface" },
  STORE: { category: "estado", hint: "repositorio central de dados" },
  BUILD: { category: "deploy", hint: "compila e empacota o projeto" },
  DEBUG: { category: "dev tools", hint: "encontrar e corrigir falhas" },
  CLONE: { category: "git", hint: "copia repositorio remoto para local" },
  MERGE: { category: "git", hint: "combina branches" },
  PARSE: { category: "dados", hint: "converte texto em estrutura" },
  PROPS: { category: "react", hint: "dados passados para componente" },
  HOOKS: { category: "react", hint: "funcoes de estado e ciclo de vida" },
  LINUX: { category: "sistema", hint: "base comum de servidores" },
  SHELL: { category: "terminal", hint: "linha de comando do sistema" },
  PANIC: { category: "runtime", hint: "erro irrecuperavel" },
  CLASS: { category: "oop", hint: "molde para criar objetos" },
  ARRAY: { category: "estrutura", hint: "colecao ordenada e indexada" },
  INDEX: { category: "database", hint: "acelera buscas em dados" },
  SCOPE: { category: "linguagem", hint: "onde variaveis existem" },
  EVENT: { category: "browser", hint: "acao capturada pelo sistema" },
  CHUNK: { category: "bundler", hint: "fragmento gerado no build" },
  PATCH: { category: "git / http", hint: "correcao aplicada ou metodo HTTP" },
  CONST: { category: "javascript", hint: "declaracao de valor constante" },
  ERROR: { category: "runtime", hint: "representa uma falha" },
  LOGIN: { category: "auth", hint: "processo de autenticacao" },
  INPUT: { category: "ui / forms", hint: "elemento que recebe dados" },
  YIELD: { category: "linguagem", hint: "pausa um generator" },
  PRINT: { category: "io", hint: "escreve no console" },
  QUEUE: { category: "estrutura", hint: "fila FIFO" },
  MUTEX: { category: "concorrencia", hint: "lock de acesso exclusivo" },
  TUPLE: { category: "tipo de dado", hint: "sequencia imutavel de valores" },
  TOKEN: { category: "seguranca / auth", hint: "credencial codificada" },
  MONGO: { category: "database", hint: "banco NoSQL orientado a documentos" },
  FLASK: { category: "framework", hint: "microframework web em Python" },
  NGINX: { category: "infra", hint: "servidor web e proxy reverso" },
  REDIS: { category: "database", hint: "banco em memoria usado como cache" },
  MYSQL: { category: "database", hint: "banco relacional popular" },
  HTTPS: { category: "protocolo", hint: "HTTP com TLS" },
  CLOUD: { category: "infra", hint: "computacao remota sob demanda" },
  GRAPH: { category: "estrutura", hint: "nos conectados por arestas" },
  BABEL: { category: "build", hint: "transpilador JavaScript" },
  REMIX: { category: "framework", hint: "framework React fullstack" },
  ASTRO: { category: "framework", hint: "sites rapidos com pouco JavaScript" },
  TURBO: { category: "build", hint: "cache e monorepo" },
  SOLID: { category: "arquitetura", hint: "principios de bom design" },
  REALM: { category: "database", hint: "banco mobile offline-first" },
  STASH: { category: "git", hint: "guarda mudancas temporarias" },
  SPAWN: { category: "processo", hint: "cria subprocesso" },
  CHMOD: { category: "linux", hint: "altera permissoes de arquivo" },
  VHOST: { category: "infra", hint: "servidor virtual por dominio" },
  KAFKA: { category: "mensageria", hint: "stream de eventos distribuido" },
  VAULT: { category: "seguranca", hint: "guarda segredos e chaves" },
  SHARD: { category: "database", hint: "divide dados em partes" },
  PIVOT: { category: "dados", hint: "reorganiza tabela ou estrategia" },
  OAUTH: { category: "auth", hint: "protocolo de autorizacao" },
  MONAD: { category: "funcional", hint: "composicao de computacoes" },
  ACTOR: { category: "concorrencia", hint: "modelo de mensagens entre processos" },
  FIBER: { category: "runtime", hint: "unidade leve de execucao" },
  IOCTL: { category: "sistema", hint: "chamada de controle de dispositivo" },
  EPOLL: { category: "linux", hint: "mecanismo de I/O nao-bloqueante" },
  UMASK: { category: "linux", hint: "mascara padrao de permissoes" },
};

export function getWordHint(word: string) {
  const normalized = word.toUpperCase();
  return (
    WORD_HINTS[normalized] ?? {
      category: WORD_CATEGORIES[normalized] ?? "tech",
      hint: `termo de ${getWordDifficulty(normalized)} usado em desenvolvimento`,
    }
  );
}

export function getWordCategory(word: string) {
  return getWordHint(word).category;
}
